dataset: # Required.
  type: cryo #pascal
  train:
    data_root: /mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4 #data/VOC2012
    data_list: /mnt/isgnas/home/vsp1/U2PL_copy/v4/v3_noRNA_test_copy.txt #/mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4/v3_noRNA.txt  #labeled.txt
    flip: True
    GaussianBlur: False
    rand_resize: [0.5, 2.0]
    #rand_rotation: [-10.0, 10.0]
    preprocess:         # added this for normalization for cryoEM - VP
      dc_filter: True
      median_filter: True
      normalize: True
    tile_size: 512
    percent_scale: [-10, 10]    # +- range of how much will we "zoom" in/out of each tile to help with flexibility in size of cells
    n_steps: 10
    crop:
      type: rand
      size: [513, 513] # crop image with HxW size
  val:
    data_root: /mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4 
    data_list: /mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4/test_high_contrast.txt  
    crop:
      type: center
      size: [513, 513] # crop image with HxW size
  batch_size: 2
  n_sup: 9   # changed for cryoem
  noise_std: 0.1
  workers: 0      # TODO: Change after debugging
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 80
  start_epochs: 0
  eval_on: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.001 # 2GPUs
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9

saver:
  snapshot_dir: checkpoints
  pretrain: ''

criterion:
  type: CELoss
  kwargs:  
    use_weight: False

net: # Required.
  num_classes: 2
  sync_bn: False
  ema_decay: 0.99
  unet:
    type: u2pl.models.unet_model.unet_call
    kwargs:
      n_channels: 3
      n_classes: 21
  encoder:
    type: u2pl.models.resnet.resnet101
    kwargs:
      multi_grid: True
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: u2pl.models.decoder.dec_deeplabv3_plus
    kwargs:
      rep_head: False
      inner_planes: 256
      dilations: [12, 24, 36]
