dataset: # Required.
  type: cryo #pascal
  train:
    data_root: /mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4 #data/VOC2012
    data_list: /mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4/v3_noRNA.txt  #v3_noRNA.txt  #labeled.txt
    rotate: True       # TODO: Edit transformations back to True
    flip: True        
    dc_filter: True
    median_filter: True
    normalize: True
    dynamic_crop: True
    percent_scale: [-10, 10]    # +- range of how much will we "zoom" in/out of each tile to help with flexibility in size of cells
  val:
    data_root: /mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4 
    data_list: /mnt/isgnas/project/ai/2023-cryoem-segmentation/data/v4/test_high_contrast.txt
    dc_filter: True
    median_filter: True
    normalize: True
  n_steps: 64   # TODO: changed for debugging
  tile_size: 512
  batch_size: 8         # TODO: Changed from 8 => 2 for debugging purposes.
  n_sup: 29              # TODO: changed for debugging
  noise_std: 0.1
  workers: 2   
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 80
  start_epochs: 0
  eval_on: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.001 
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9

saver:
  snapshot_dir: checkpoints
  pretrain: ''

criterion:
  type: CELoss
  kwargs:  
    use_weight: False

net: # Required.
  num_classes: 2
  sync_bn: False
  ema_decay: 0.99
  unet:
    type: u2pl.models.unet_model.unet_call
    kwargs:
      n_channels: 3
      n_classes: 21
  encoder:
    type: u2pl.models.resnet.resnet101
    kwargs:
      multi_grid: True
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: u2pl.models.decoder.dec_deeplabv3_plus
    kwargs:
      rep_head: False
      inner_planes: 256
      dilations: [12, 24, 36]
